---
title: "爱自己"
author: "亚云"
date: "2023-02-01"
categories: [生活, 救赎]
---

今天看到一位我很尊敬的前辈发的post, 里面谈到关于how to make peace with yourself and others这个话题，不禁引起我的思考。相比于过去，我对于现在的状态很满意。我大约是这一两年来才逐渐 find peace of mind. 我主要做了三件事情：**找therapist聊；跟原生家庭划清界限；有意识地自我优先。**

我一共找过三位therapist, 和其中两位只聊过一次，和剩下那位聊过五六次。和我聊过最多的这位therapist对我帮助很大。她本身是一个温柔如水的台湾姐姐，比我年长10-20岁的样子。我的原生家庭沟通方式是偏执的，强烈的，甚至歇斯底里的争辩。我和我的母亲之间，爱很强烈，也很让我受伤。之前写过一篇关于原生家庭的[文章](https://mp.weixin.qq.com/s/mKYKIIjxqccVQ66AAxDsqw)，这里就不多说了。而这位温柔的therapist, 她的话语让我如沐春风。她纠正了我和父母原有的相处方式，帮助我建立真正地对我好也对父母好的新关系。

和原生家庭划清界限，是我花了这么多年才意识到和纠正过来的事情。自从不再逼迫自己做一个所谓"孝顺"的子女，不再逼迫自己每周必须给母亲打电话（常常打完电话我都会很累并且情绪烦躁），我这几个月的状态 ---- 安静，祥和，心静如水。我实在是太喜欢这种情绪不被打扰的感觉了。

能每时每刻做到"自我优先"对我来说是极其困难的。从小耳濡目染母亲的忍辱负重，再加上我从来都是一个怕给别人添麻烦的人，导致我很难开口聊自己的需求。比如和朋友们出去旅行，我一定不会是第一个说出想休息或者想找卫生间上厕所的那个人；在飞机上如果没能坐在过道附近的话，我一定会等到必须要上厕所的时候才麻烦旁边的乘客起身。中国有句老话，滴水之恩当涌泉相报，完全就是我大部分时候的状态。因此，我开始有意识地开始训练"自我优先"。比如，第一时间表达自己的情绪和需求；允许自己在忙的时候先暂时不回复别人的消息等等。通过这种小事的训练，现在的我更加自信从容，更加珍惜自己的时间价值和情绪价值，并且更有精力做重要的事。

爱自己这件事和其他任何事情一样，都是可以学习和训练的。很欣慰这段时间的进步，继续保持 :)
