---
title: "About"
---

My name is Yayun Jin, and I\'m a writer and machine learning engineer. Growing up in China, I moved to the U.S. to pursue my academic interests, and now live in the Bay Area.

Here are my beliefs and values (and my interpretations): 

-   **Wisdom.** One of my favorite quote is: Grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference

-   **Peacefulness**. This the state of being quiet and calm; the state of not being worried or disturbed in any way. In Kung Fu Panda, Oogway said: Yesterday is history, Tomorrow is a mystery, but Today is a gift. That is why it is called the present. So enjoy the present :)

-   **Freedom**. The ability to feel free physically, financially, and mentally. 

-   **Health & Fitness**. there is a famous slogan in China that everyone jokes about but it really deserves to be taken seriously: 每天锻炼1小时，健康工作50年, 幸福生活一辈子. A translation into English would be -- If you exercise one hour a day, you can work healthily for 50 years, and live a long, happy life.

-   **Community**. There is something privileged about me. All of us are privileged in some way. Support systems are based on caring for each other.

\

What keeps me busy these days is:

-   Working as a machine learning engineer at Microsoft. To support all data centers worldwide, my team determines how much space and power Microsoft Azure needs. 

-   Managing a non-profit organization dedicated to building a community for professionals and to helping each other grow. This is us: <https://www.careerupclub.org/>

-   Teaching machine learning on YouTube for FREE. I believe that knowledge and information should be freely accessible to everyone. 

-   Creating short videos about interview preparation, resume editing, and career development on [小红书](https://www.xiaohongshu.com/user/profile/5f41ed87000000000101f948?xhsshare=CopyLink&appuid=5f41ed87000000000101f948&apptime=1675622900) and 微信视频号.

-   Coaching people to achieve greater fulfillment in their lives.

-   Blogging about my thoughts and the \"aha\" moments in my life.
