---
title: "Recommendation"
---

These are the things that changed my lifestyle/mindset and I highly recommend you give them a read/try!

### Coding:

[Leetcode](https://leetcode.com/): I practice coding and interviewing here

[AlgoMonster](https://algo.monster/): Here I start practicing algorithm questions systematically (strongly recommended for beginners or for those who find leetcode problems overwhelming)

### Life style/Mindset

[The 4-hour Workweek](https://a.co/d/3egSVG2)

I would say, without looking up again, what I learned from this book:

The value of money changes in different geographical locations; outsourcing your life; mini-retirement. \

[The 7 Habits of Highly Effective People](https://a.co/d/3sDZiwN)

Since reading this book, I have been following the 7 habits every single day.

### Finance

[会走路的钱（上）](https://a.co/d/inrNox2), [会走路的钱（下）](https://a.co/d/dzk5rFC)

I have never read a better book about personal finance than this one. Please note that this book is written in Chinese. 

### YouTubers

[Ali Abdaal](https://www.youtube.com/@aliabdaal/): The motivation I get from him is immense.  

\

### Skillcare

Dermatica: <https://www.dermatica.com/referrer/Z9W0WL>

I've been using it since mid-2022.  Give it a shot if you're interested in science-based skillcare. (As a matter of transparency, this is my referral link. You get the first month free + 25% off next month, and I get \$6.25.)
