---
title: "莫名的烦躁"
author: "亚云"
date: "2023-02-16"
categories: [思考, 生活]
---

每个月总有那么几天很烦躁，大多是都是生理期要来的前几天。这个月，因为换发护照的一点点小事，直接把我整"抑郁"了，还专门请了一天的病假。

每次烦躁的时候，我都会首先让自己深呼吸，然后反问自己，这个事值当这么烦躁吗？然后每次都能想到之前参加什么讲座之类的记下的一句话：don't sweat on small things. 

可能在很多人看来，我都是精力充沛正能量满满的一个人。事实上确实如此，大部分都是这样，然而并不能抵消到我小部分时间也会很烦躁到啥也不想干的状态。发现一个有趣的现象，越是烦躁，越是忍不住刷手机，然后更加烦躁。所以我现在的办法是，尽快让自己冷静下来。如果不想做手头的事就不再勉强自己，而是选择做一些让自己平静的事，比如写日记啦，看一些YouTube长视频之类的，看书摘啦。总之，远离手机，远离短视频。

除了生理周期的变化，归根结底还是有一些事是让我烦躁的。比如，我的工作一直还挺忙，而且每次工作的事情来得比较急；工作之外的学习计划往往总是进度慢于期望，容易轻度焦虑；自己的side business常常在long-term和short-term priorities中来回动荡，总是因为没办法花太多时间精力去做而感到愧疚；负责的non profit comunity的活动时常也会因为我过于谨慎害怕出错而精神紧张。

\

唉，真是又上进努力又容易自找麻烦。

所以接下来，我需要一件件去解决这些事情。

-   首先，工作上的事：提高效率，不懂就问，over communication, 该干啥干啥，天塌下来有manager挡着，别担心；

-   然后，我的学习计划：提升优先级，充分贯彻reverse learning，don't overestimate what I can do in a day; and don't underestimate what I can do in a year. 每天进步一点点就很棒了！

-   接着，side business：和我的学习计划相结合，别太纠结质量，现阶段数量更重要！

-   最后，多delegate任务给其他人，我就负责ideation和创建团队，容许团队出问题，容许结果不那么完美。

路漫漫其修远兮，吾将上下而求索。人生啊\...\...\...
