---
title: "新年思考：假如生命只有三天"
author: "亚云"
date: "2023-02-17"
categories: [珍惜, 反复读]
---

没错，这个话题我一直想认真思考一下，结果2月都过半了，才有时间好好写一下。

<center>

### **当生命只有1天：**

</center>

完了，连当天回国的机票都不一定能买到，即使能买到，还要在飞机上度过十几个小时，不舒服也吃不好。所以，我就哪儿不去了，赶紧和虾米交代一下我的后事（主要是遗产），然后给妈妈爸爸姐姐弟弟打电话，再给姨姨舅舅表姐表哥们打电话，让他们照顾好我妈。然后去最近的海边，躺在虾米怀里，告诉他我很开心能遇到他，谢谢陪我走过人生的最后一程，然后静静死去。（哎，写到这里眼眶都湿了）

\

<center>

### **当生命只剩3天：**

</center>

马上回国。回到小时候的家，去和妈妈一起抱头痛哭，然后见一圈家人，太远的亲戚就算了。然后好吃好喝，漂个头发，搞个奇奇怪怪的颜色（因为一直担心伤头发，从来没漂过发，但就剩三天了，伤了就伤了）。

\

<center>

### **当生命只剩3个月：**

</center>

马上回国。然后赶紧带妈妈爸爸姐姐外甥去国内各种旅行，完全不设budget那种旅行。

\

<center>

### **当生命只剩1年：**

</center>

和只剩3个月做的事一样。

\

<center>

### **当生命只剩3年：**

</center>

写文章，记录下来生命倒计时。算了下我的积蓄也够我三年的开销了，所以我是不会去工作的。多陪陪家人，做自己一直想做但没机会做的事，包括去日本看樱花吃东西，去韩国买衣服，去泰国看大象，去太平洋各种小岛浮潜。

\

<center>

### **当生命还剩10年：**

</center>

不着急挣钱了。虽然还是得工作，但是选择一个work balance超好的工作。把上面自己想做的事都做了。生两个孩子，好好陪伴他们的童年，在我要离开他们的时候编个童话故事，[从此我也是活在童话世界里的人了。]{.underline}

\

<center>

### **当生命还剩30年：**

</center>

稍微需要努力一点点工作，多赚些钱。但是work life balance还是最重要的。每年花一个月回国陪家人，带家人旅行。生一个孩子，把他抚养成人。写作，记录生活。

\

<center>

### **当生命还剩50年：**

</center>

更加努力一点点工作，多赚些钱。家人永远是第一位的。从现在开始，每年回国。趁着父母尚健在，珍惜时光。生一个孩子，把他抚养成人。写作，记录生活。

\
\

天啊！在写之前，我完全没意识到家人对我的重要程度和"我想要生孩子"这件事情。我的思绪在绝大部分时间，全部被日常的忙碌和看似重要的小事所占据。而写完这些字，我忽然感到，生活中绝大部分我在做的事都没有那么重要了。我更加理解了什么是"活在当下"。我每一天的"多活"，都是恩赐，不要浪费时光去焦虑，而是好好享受当下。

\

从今天起，好好吃每一顿饭，珍惜身边人，陪伴家人。

\

[*这篇文章我以后会拿出来反复看。*]{.underline}
